### ISSUE TITLE
Conecting failed

### ISSUE THREAD

**Issue by jswetzen** [Treblesteph/oh-nokiahealth-integration#40]
#
![Screenshot_20220605-102008_Trebuchet](https://user-images.githubusercontent.com/3224510/172041995-85610c53-fac0-4c25-8633-29adb066f568.png)

Just tried connecting Withings, but this.is what I get.

**Comment by gedankenstuecke** [comment]
Hey @jswetzen, thanks for reporting this! It seems when we updated our frontend-templates we forgot to set up that correct route! I've just fixed it and gave it a try, it works now on my end. 😄

**Comment by jswetzen** [comment]
Thanks for the quick fix Bastian! I'm afraid it now fails with "KeyError 'userid' at /complete/nokia". Could it be that I have several users in my Withings account? I did get to choose the user in the Withings connection authorization, but maybe it's not supported on the OH end?

------- Original Message -------

**Comment by jswetzen** [comment]
@gedankenstuecke It seems to be a change in the Withngs API, `rjson` has this value:

```
{'errors': [{'message': 'Not Found: for more information, see https://support.withings.com/hc/en-us/article/360016745358--BREAKING-Deprecating-access-and-refresh-tokens-endpoints'}]}
```

**Comment by gedankenstuecke** [comment]
@jswetzen Thanks for looking into this and giving it a try! I've updated the API integration in accordance to their changes for the OAuth2 flow. I just gave it a try with my own account and it seems to work so far, at least for the login/auth flow.

Having said this: I've never used any Withings/Nokia device, so my account doesn't have any data in it, so I can't verify whether the data export works as it should. Would you be willing to check whether it worked for you? :-)

**Comment by jswetzen** [comment]
It's working! Nice job 🎉 😄

**Comment by gedankenstuecke** [comment]
Great, glad to hear that it works now!
