### ISSUE TITLE
rate limiting

### ISSUE THREAD

**Issue by Treblesteph** [Treblesteph/oh-nokiahealth-integration#9]

**Comment by Treblesteph** [comment]
<img width="778" alt="screenshot 2018-04-05 12 45 55" src="https://user-images.githubusercontent.com/4573291/38426000-4ec091c0-39ad-11e8-938f-b7e458cc6e69.png">

**Comment by mcescalante** [comment]
Closed with 770c46a by adding `requests-respectful`

**Comment by Treblesteph** [comment]
reopening because I don't think all these are being adhered to, the only reason we aren't hitting limits is that there isn't a lot of data in my account
